# Alpine Linux é bem menor que as outras distribuições
FROM nginx:alpine

# Cópia dos arquivos de configuração
COPY http.conf /etc/nginx/nginx.conf

# Cópia do certificado Diffie-Hellman parameter
COPY ./certificados/dhparam.pem /certificados/dhparam.pem
